# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: mix
    directory: /
    schedule:
      interval: monthly
    groups:
      non-breaking-changes:
        update-types:
        - minor
        - patch

  - package-ecosystem: npm
    directory: /assets
    schedule:
      interval: monthly
    groups:
      non-breaking-changes:
        update-types:
        - minor
        - patch
