ARG DEBIAN_VERSION
FROM debian:${DEBIAN_VERSION}

RUN apt-get update && apt-get install -y --no-install-recommends -q2 \
  nodejs \
  npm \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /build/
WORKDIR /build/
RUN npm install -ci -no-audit @mapbox/spritezero

COPY spritezero.js /build/

ENTRYPOINT ["/usr/bin/node", "/build/spritezero.js"]
