ARG DEBIAN_VERSION
FROM debian:${DEBIAN_VERSION} AS build

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  ca-certificates \
  default-jdk \
  unzip \
  wget \
  && rm -rf /var/lib/apt/lists/*

ENV GRADLE_VERSION=9.3.1
ENV GRADLE_HOME=/gradle
RUN wget --no-verbose --output-document /tmp/gradle.zip https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip \
  && mkdir ${GRADLE_HOME} \
  && unzip -q -d /gradle/ /tmp/gradle.zip \
  && rm /tmp/gradle.zip
ENV PATH=${GRADLE_HOME}/gradle-${GRADLE_VERSION}/bin:${PATH}
ENV GRADLE_OPTS='-Dorg.gradle.daemon=false'

ARG MLT_VERSION=82de11da8498e34071a7b253482d705ebd534256
RUN \
  wget https://github.com/breunigs/maplibre-tile-spec/archive/${MLT_VERSION}.tar.gz -O maplibre-tile-spec.tar.gz && \
  tar zxf maplibre-tile-spec.tar.gz && rm maplibre-tile-spec.tar.gz && mv maplibre-tile-spec* /maplibre-tile-spec

RUN mkdir -p /build/
COPY mlt-converter/ /build/

RUN cd /build/ \
  && /usr/bin/chrt --idle 0 \
  /usr/bin/nice -n19 \
  /usr/bin/ionice --class idle \
  gradle build --parallel

ARG DEBIAN_VERSION
FROM debian:${DEBIAN_VERSION} AS run

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
  default-jre \
  && rm -rf /var/lib/apt/lists/*

COPY --from=build /build/build/libs/mlt-converter-1.0.0-all.jar /mlt-converter.jar

ENTRYPOINT [ \
  "/usr/bin/chrt", "--idle", "0", \
  "/usr/bin/nice", "-n19", \
  "/usr/bin/ionice", "--class", "idle", \
  "/usr/bin/java", \
  "-Dcom.google.protobuf.use_unsafe_pre22_gencode", \
  "-cp", "/mlt-converter.jar", \
  "Converter" \
  ]
