FROM debian:testing-slim

RUN apt-get -y update \
  && apt-get -y install --no-install-recommends \
  brotli \
  findutils \
  gzip \
  osmium-tool \
  tilemaker \
  unzip \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /workdir
