defmodule Data.AutoGenerated.Video.Rendered_033ce7d09d87db3baba2f346047cc409 do
  @moduledoc "#{"halstenbek-vr3: Halstenbek: Rellingen Kellerstraße → Bickbargen"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "halstenbek-vr3: Halstenbek: Rellingen Kellerstraße → Bickbargen"
  end

  @impl Video.Rendered
  def hash() do
    "033ce7d09d87db3baba2f346047cc409"
  end

  @impl Video.Rendered
  def length_ms() do
    60525
  end

  @impl Video.Rendered
  def sources() do
    [
      {"2025-03-18-halsten/GX018471", :start, "00:00:43.762"},
      {"2025-03-18-halsten/GX018470", "00:00:11.003", "00:00:28.033"}
    ]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %{
      __struct__: Geo.BoundingBox,
      max_lat: 53.6284886,
      max_lon: 9.8701753,
      min_lat: 53.6167584,
      min_lon: 9.8616915
    }
  end

  @impl Video.Rendered
  def renderer() do
    6
  end

  @impl Video.Rendered
  def recording_dates() do
    [%{text: "März 2025", timestamp: 0}]
  end

  @impl Video.Rendered
  def street_names() do
    [
      %{text: "Altonaer Straße", timestamp: 0},
      %{text: "Gärtnerstraße", timestamp: 4240},
      %{text: "Lübzer Straße", timestamp: 6880},
      %{text: "Bickbargen", timestamp: 32060},
      %{text: "Seestraße", timestamp: 59885}
    ]
  end

  @impl Video.Rendered
  def timed_polyline() do
    "qcfheB}tlyQ?pBbCwQdBxBwQtB`DwVfCvDwQ~A|DwQ~@~F_SArHwQi@hG_Xs@jFwVIbFwQt@`BwQxA?oUpA_DwQd@cEgThBoCwQjClAwVvAhBoUdBdAwQzCtAoUbDu@wQjBcCwQzAoAgTrBmDwQ`BsEoUzBiDwQjCbAwQ|BpDgTvCjEwQpDlEwVnD`EwQxCjDoUfD|DwQpDpEoUrDxEwQvDtFwVzCvEwQrDfFoUbDjEwQdEfGwVhDpEwQrDxEoU`DtDwQvDlEoUjDpDwQpEtEwVzDfEwQnDhEoUfDrDwQ|DpEoUvDhEwQbEnEwVpDjEwQ|ChDoUjDvDwQ~DrEwV~CxDwQrCdDoUvD|D_SjCdDgTzCvDwQtDpEwVpCpDwQtChEoUnClEwQtCfFoUxCzFwQ`DnGwV|CbGwQhC~EoUhCtFwQrCdGoUtC`GwQ~C~GwVvCfHwQdC~FoUpCvGwQ`DzGoUzCzGwQnC`GwVfDlHwQ|BpFoUnCbGwQzCrGwVrChGwQ`ClFoUnCzFwQtCfGoUrCpGwQdCbFwQbC|EgTfCfFwQjCvFoUhCvFwQxB|EwQpBnEgTdBtCwQbDJwV`CmDwQhCqEoUbCgDwQ`DyEoUhD{DwQdD{EwVzCkFwQrCeEoUbDmEwQxDmEoUbEmDwQrDiDwVhEoEwQzCmDoUfDgEwQpDsEoUnD}EwQ|C_EwQbD{DgThDgEwQ`EcFwVzCqDwQfC}CoUtCoDwQlCcDoUfBwDwQtCaEwVbBkAwQn@q@oUJGwQB?oUFKwQp@qAwVbBeCwQ@UeKrCwDsSxD{DwQfCcCoUlCoCwQdCeCwVbCeCwQhBqBoUrBaCwQpB{BoUfBuBwQtA}BwQpAoCgTxAeDwQfBoCoU|AwBwQbBeBwQdBoBgTnCiBwQpBeAoUrB{AwQhBwBoUvAmBwQhB{BwV`B_BwQ|AcBwV`BsCwQ`AcCoUhA_CwQvA}AoUtAqAwQpAwAwQlAsAgTtAiBwQzAiCoUrA}CwQvAyBwQ|AcBgTzBqBwQrAqAwQdBcB_ShBmBwQxBcCwQnBsBgTvBsCwQ~AwBwQbB{BgT`B{AwQ|@g@wQp@s@_Sn@k@wQhA`@wQpAhAgTpBbBwQ"
  end
end
