defmodule Data.AutoGenerated.Video.Rendered_2109ffb363916b8b6e2105a973337974 do
  @moduledoc "#{"2021-12-18-bahnquerung-hafenbahn: vom Bostelbeker Hauptdeich zur Blohmstraße"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "2021-12-18-bahnquerung-hafenbahn: vom Bostelbeker Hauptdeich zur Blohmstraße"
  end

  @impl Video.Rendered
  def hash() do
    "2109ffb363916b8b6e2105a973337974"
  end

  @impl Video.Rendered
  def length_ms() do
    43761
  end

  @impl Video.Rendered
  def sources() do
    [
      {"2022-05-01-velo11-u-velo10-ab-harburg/GX013685", "00:02:57.978", "00:03:14.061"},
      {"2022-05-01-velo11-u-velo10-ab-harburg/GX013687", "00:03:00.013", "00:03:27.941"}
    ]
  end

  @impl Video.Rendered
  def rendered?() do
    false
  end

  @impl Video.Rendered
  def bbox() do
    %Geo.BoundingBox{
      maxLat: 53.469739387387385,
      maxLon: 9.98400964167916,
      minLat: 53.465107,
      minLon: 9.967990558558558
    }
  end

  @impl Video.Rendered
  def renderer() do
    3
  end

  @impl Video.Rendered
  def metadata() do
    [{0, "Mai 2022"}]
  end

  @impl Video.Rendered
  def coords() do
    [
      %Video.TimedPoint{lat: 53.469739387387385, lon: 9.967990558558558, time_offset_ms: 0},
      %Video.TimedPoint{lat: 53.469732, lon: 9.96806, time_offset_ms: 164},
      %Video.TimedPoint{lat: 53.469717, lon: 9.968201, time_offset_ms: 498},
      %Video.TimedPoint{lat: 53.469703, lon: 9.968341, time_offset_ms: 831},
      %Video.TimedPoint{lat: 53.469689, lon: 9.968476, time_offset_ms: 1165},
      %Video.TimedPoint{lat: 53.469678, lon: 9.968615, time_offset_ms: 1499},
      %Video.TimedPoint{lat: 53.469665, lon: 9.968758, time_offset_ms: 1832},
      %Video.TimedPoint{lat: 53.469654, lon: 9.9689, time_offset_ms: 2166},
      %Video.TimedPoint{lat: 53.469644, lon: 9.969042, time_offset_ms: 2499},
      %Video.TimedPoint{lat: 53.469631, lon: 9.969185, time_offset_ms: 2833},
      %Video.TimedPoint{lat: 53.469618, lon: 9.969327, time_offset_ms: 3167},
      %Video.TimedPoint{lat: 53.469604, lon: 9.96947, time_offset_ms: 3500},
      %Video.TimedPoint{lat: 53.469584, lon: 9.969607, time_offset_ms: 3834},
      %Video.TimedPoint{lat: 53.469555, lon: 9.969744, time_offset_ms: 4167},
      %Video.TimedPoint{lat: 53.469525, lon: 9.969881, time_offset_ms: 4501},
      %Video.TimedPoint{lat: 53.469493, lon: 9.970021, time_offset_ms: 4835},
      %Video.TimedPoint{lat: 53.469457, lon: 9.970152, time_offset_ms: 5168},
      %Video.TimedPoint{lat: 53.469412, lon: 9.970277, time_offset_ms: 5502},
      %Video.TimedPoint{lat: 53.469372, lon: 9.970405, time_offset_ms: 5835},
      %Video.TimedPoint{lat: 53.469356, lon: 9.970537, time_offset_ms: 6169},
      %Video.TimedPoint{lat: 53.469361, lon: 9.970677, time_offset_ms: 6503},
      %Video.TimedPoint{lat: 53.469367, lon: 9.970818, time_offset_ms: 6836},
      %Video.TimedPoint{lat: 53.469359, lon: 9.970954, time_offset_ms: 7170},
      %Video.TimedPoint{lat: 53.469332, lon: 9.971082, time_offset_ms: 7503},
      %Video.TimedPoint{lat: 53.469291, lon: 9.9712, time_offset_ms: 7837},
      %Video.TimedPoint{lat: 53.469244, lon: 9.971306, time_offset_ms: 8171},
      %Video.TimedPoint{lat: 53.469195, lon: 9.971413, time_offset_ms: 8504},
      %Video.TimedPoint{lat: 53.46914, lon: 9.97152, time_offset_ms: 8838},
      %Video.TimedPoint{lat: 53.469085, lon: 9.971622, time_offset_ms: 9171},
      %Video.TimedPoint{lat: 53.469026, lon: 9.97172, time_offset_ms: 9505},
      %Video.TimedPoint{lat: 53.468967, lon: 9.97182, time_offset_ms: 9839},
      %Video.TimedPoint{lat: 53.468912, lon: 9.97192, time_offset_ms: 10172},
      %Video.TimedPoint{lat: 53.468857, lon: 9.972018, time_offset_ms: 10506},
      %Video.TimedPoint{lat: 53.468802, lon: 9.972119, time_offset_ms: 10839},
      %Video.TimedPoint{lat: 53.468749, lon: 9.972221, time_offset_ms: 11173},
      %Video.TimedPoint{lat: 53.468695, lon: 9.972325, time_offset_ms: 11507},
      %Video.TimedPoint{lat: 53.468639, lon: 9.972431, time_offset_ms: 11840},
      %Video.TimedPoint{lat: 53.468583, lon: 9.972534, time_offset_ms: 12174},
      %Video.TimedPoint{lat: 53.468526, lon: 9.972638, time_offset_ms: 12507},
      %Video.TimedPoint{lat: 53.468466, lon: 9.972742, time_offset_ms: 12841},
      %Video.TimedPoint{lat: 53.468408, lon: 9.972846, time_offset_ms: 13175},
      %Video.TimedPoint{lat: 53.468353, lon: 9.972954, time_offset_ms: 13508},
      %Video.TimedPoint{lat: 53.468299, lon: 9.973067, time_offset_ms: 13842},
      %Video.TimedPoint{lat: 53.468241, lon: 9.973171, time_offset_ms: 14175},
      %Video.TimedPoint{lat: 53.468184, lon: 9.973279, time_offset_ms: 14509},
      %Video.TimedPoint{lat: 53.468122, lon: 9.973385, time_offset_ms: 14843},
      %Video.TimedPoint{lat: 53.468064, lon: 9.973484, time_offset_ms: 15176},
      %Video.TimedPoint{lat: 53.468009, lon: 9.97358, time_offset_ms: 15510},
      %Video.TimedPoint{lat: 53.46719923388306, lon: 9.975397421289355, time_offset_ms: 15833},
      %Video.TimedPoint{lat: 53.467085, lon: 9.975546, time_offset_ms: 16331},
      %Video.TimedPoint{lat: 53.466952, lon: 9.975762, time_offset_ms: 16998},
      %Video.TimedPoint{lat: 53.466828, lon: 9.976004, time_offset_ms: 17665},
      %Video.TimedPoint{lat: 53.466046, lon: 9.977659, time_offset_ms: 22002},
      %Video.TimedPoint{lat: 53.465949, lon: 9.977914, time_offset_ms: 22669},
      %Video.TimedPoint{lat: 53.465604, lon: 9.978609, time_offset_ms: 24671},
      %Video.TimedPoint{lat: 53.465482, lon: 9.978824, time_offset_ms: 25338},
      %Video.TimedPoint{lat: 53.465215, lon: 9.979204, time_offset_ms: 26673},
      %Video.TimedPoint{lat: 53.465153, lon: 9.979311, time_offset_ms: 27006},
      %Video.TimedPoint{lat: 53.465116, lon: 9.979441, time_offset_ms: 27340},
      %Video.TimedPoint{lat: 53.465107, lon: 9.979588, time_offset_ms: 27673},
      %Video.TimedPoint{lat: 53.465126, lon: 9.979731, time_offset_ms: 28007},
      %Video.TimedPoint{lat: 53.465183, lon: 9.979843, time_offset_ms: 28341},
      %Video.TimedPoint{lat: 53.465256, lon: 9.979915, time_offset_ms: 28674},
      %Video.TimedPoint{lat: 53.465496, lon: 9.980102, time_offset_ms: 29675},
      %Video.TimedPoint{lat: 53.466268, lon: 9.98066, time_offset_ms: 32677},
      %Video.TimedPoint{lat: 53.466524, lon: 9.980861, time_offset_ms: 33678},
      %Video.TimedPoint{lat: 53.467128, lon: 9.981282, time_offset_ms: 36013},
      %Video.TimedPoint{lat: 53.467208, lon: 9.981375, time_offset_ms: 36347},
      %Video.TimedPoint{lat: 53.467258, lon: 9.981515, time_offset_ms: 36681},
      %Video.TimedPoint{lat: 53.467259, lon: 9.981674, time_offset_ms: 37014},
      %Video.TimedPoint{lat: 53.467126, lon: 9.98227, time_offset_ms: 38349},
      %Video.TimedPoint{lat: 53.46704, lon: 9.982695, time_offset_ms: 39349},
      %Video.TimedPoint{lat: 53.466914, lon: 9.983223, time_offset_ms: 40684},
      %Video.TimedPoint{lat: 53.466812, lon: 9.983741, time_offset_ms: 42018},
      %Video.TimedPoint{lat: 53.466763, lon: 9.983824, time_offset_ms: 42352},
      %Video.TimedPoint{lat: 53.466588, lon: 9.983932, time_offset_ms: 43353},
      %Video.TimedPoint{lat: 53.466538, lon: 9.983993, time_offset_ms: 43686},
      %Video.TimedPoint{lat: 53.466529904047974, lon: 9.98400964167916, time_offset_ms: 43761}
    ]
  end
end