defmodule Data.AutoGenerated.Video.Rendered_3434c719d638ac6a2c58489a2f0ae773 do
  @moduledoc "#{"2023-10-29-lenhartzstrasse: Lenhartzstraße → Schottmüllerstraße → Eppendorfer Marktplatz"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "2023-10-29-lenhartzstrasse: Lenhartzstraße → Schottmüllerstraße → Eppendorfer Marktplatz"
  end

  @impl Video.Rendered
  def hash() do
    "3434c719d638ac6a2c58489a2f0ae773"
  end

  @impl Video.Rendered
  def length_ms() do
    66112
  end

  @impl Video.Rendered
  def sources() do
    [
      {"2026-02-15-eims/GX018760", "00:00:45.193", :end},
      {"2026-02-15-eims/GX018761", :start, "00:00:42.122"},
      {"2026-02-15-eims/GX018762", :start, "00:00:17.442"}
    ]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %{
      __struct__: Geo.BoundingBox,
      maxLat: 53.5931052083333,
      maxLon: 9.989283,
      minLat: 53.5856595,
      minLon: 9.981965
    }
  end

  @impl Video.Rendered
  def renderer() do
    6
  end

  @impl Video.Rendered
  def recording_dates() do
    [%{text: "Februar 2026", timestamp: 0}]
  end

  @impl Video.Rendered
  def street_names() do
    [
      %{text: "Lenhartzstraße", timestamp: 0},
      %{text: "Schottmüllerstraße", timestamp: 20222},
      %{text: "Eppendorfer Landstraße", timestamp: 36202},
      %{text: "Eppendorfer Marktplatz", timestamp: 63637}
    ]
  end

  @impl Video.Rendered
  def timed_polyline() do
    "wnreeBgbg`R?gBm@wQwBc@wQaCUgTsC?wQ_CGoUwCEwQeDj@oUeDtAwQkCn@wVyDPwQoCIoU}Bc@wQeCi@wVcCMwQiBKoUmCOwQkBBwQaBSgTcEmBwQGSoA}BqAed@M?eRg@IwQmAu@wQ_Bm@_SgBk@wQuCw@wQ}Bk@wQqC[gTcEkAgTcCw@wQyDsAwQuCs@oU{Cs@wQgDg@oUgDk@wQmDaAwVgDo@_SkCa@gT}C]wQeD[oUiDk@wQ_D_AwQ}Cs@gTeDy@wQsD}@oUsDgAwQ{CaAwQuCgAgTkDuAwQ{C_BoU}CeCwQwB{CwQ}BaCgTyCoBwQqCeBoUuCoBwQgCaBwQcCeBgTsCoBwQcCaBwQeCkAgTmCsAwQcCkCoUuBeEwQ_CyEwVqBuDwQkC_EoU}ByDwQ_DkFwVgC}DwQwB{CoUgCkDwQ}BqDoUeBiDwQoCcEwVeAyEwQiBkDoU_BqDwQ{B_DoUsBgEwQmB{DwQiByDgT_CeEwQiBeFwVcCkEwQcBmDoUiBuDwQkCmBoU}AsDwQ_BwEwVaBiDwQ{BqCoUaCyCwQqBsDoUoBkDwQwBkEwVaBqDwQqD}GoUwBgDwQi@_DoUk@oDwQOsDwV@oEwQEmDoUSmEwQIkEwVQ{DwQIcDoU?iDwQhAiGoUt@kAwQb@c@wQb@a@oUhCmAwQdAPoUbAXwQt@IoUbA^wQfBl@_X|CvA_XdC`AwVbCjAwQn@~@wQ|A~@gT~BjAwQtBfAoUpBbAwQpBnAoUnCrAwQnBjAoUpBx@wQxBp@wQ`CrAoUhCpAwQ~BpAwQpB`AwQxBhAwQpB`AoUxBjAwQ|BfAoUpBhAwQfCjAwVnB|@wQ~Ar@oUrAn@wQ`ADoUb@w@wQLA_I@DgH@MeRV{AwVTcBwQ_@aBoUi@gAwQaBwAoUqBq@wQgBi@wQsBc@gTiCs@wQoCkAwVeC}AwQcBeBoUiC_DwQiC{BoUqCaAwQkCcBwVqBaAwQgCmAoUsBkBwQ{CgAwViCkAwQsBe@oUoBw@wQiBGoUqBg@wQ}B_@wVyBg@wQqBe@oUaBaAwQ}B{AoUcCs@wQeCkAwVyBcDwQiBiAoUoBmDwQeCgFwVcBcDwQ_BgCoUmB{BwQaBaCoUcB{BwQiBiCwVmBwBwQyAsAoU_AeAwQqAiAoU}Ap@wQqApBwViBbEwQOBwBuDz@mo@"
  end
end
