defmodule Data.AutoGenerated.Video.Rendered_5880d9280260e337f3a04d2fe7f5c188 do
  @moduledoc "#{"2022-01-27-versuchsradweg-beim-schlump: Beim Schlump Richtung Harvestehude"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "2022-01-27-versuchsradweg-beim-schlump: Beim Schlump Richtung Harvestehude"
  end

  @impl Video.Rendered
  def hash() do
    "5880d9280260e337f3a04d2fe7f5c188"
  end

  @impl Video.Rendered
  def length_ms() do
    16816
  end

  @impl Video.Rendered
  def sources() do
    [
      {"2022-01-08-rothenbaumchaussee/GX013101", "00:00:03.937", :end},
      {"2022-01-08-rothenbaumchaussee/GX013102", "00:00:02.269", "00:00:12.279"}
    ]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %Geo.BoundingBox{
      maxLat: 53.57114964564565,
      maxLon: 9.977289222222222,
      minLat: 53.56765590990991,
      minLon: 9.970839666666667
    }
  end

  @impl Video.Rendered
  def renderer() do
    2
  end

  @impl Video.Rendered
  def coords() do
    [
      %Video.TimedPoint{lat: 53.56765590990991, lon: 9.970839666666667, time_offset_ms: 0},
      %Video.TimedPoint{lat: 53.567668, lon: 9.970869, time_offset_ms: 66},
      %Video.TimedPoint{lat: 53.56773, lon: 9.971011, time_offset_ms: 400},
      %Video.TimedPoint{lat: 53.567793, lon: 9.971159, time_offset_ms: 733},
      %Video.TimedPoint{lat: 53.567853, lon: 9.971302, time_offset_ms: 1067},
      %Video.TimedPoint{lat: 53.567918, lon: 9.971444, time_offset_ms: 1401},
      %Video.TimedPoint{lat: 53.567984, lon: 9.971593, time_offset_ms: 1734},
      %Video.TimedPoint{lat: 53.568039, lon: 9.971743, time_offset_ms: 2068},
      %Video.TimedPoint{lat: 53.568092, lon: 9.971891, time_offset_ms: 2401},
      %Video.TimedPoint{lat: 53.568164, lon: 9.972041, time_offset_ms: 2735},
      %Video.TimedPoint{lat: 53.568239, lon: 9.972193, time_offset_ms: 3069},
      %Video.TimedPoint{lat: 53.568313, lon: 9.972347, time_offset_ms: 3402},
      %Video.TimedPoint{lat: 53.568389, lon: 9.972511, time_offset_ms: 3736},
      %Video.TimedPoint{lat: 53.568465, lon: 9.972671, time_offset_ms: 4069},
      %Video.TimedPoint{lat: 53.56854, lon: 9.972837, time_offset_ms: 4403},
      %Video.TimedPoint{lat: 53.56862, lon: 9.973004, time_offset_ms: 4737},
      %Video.TimedPoint{lat: 53.568692, lon: 9.97318, time_offset_ms: 5070},
      %Video.TimedPoint{lat: 53.568759, lon: 9.973356, time_offset_ms: 5404},
      %Video.TimedPoint{lat: 53.568836, lon: 9.973524, time_offset_ms: 5737},
      %Video.TimedPoint{lat: 53.568908, lon: 9.973665, time_offset_ms: 6071},
      %Video.TimedPoint{lat: 53.568959, lon: 9.973771, time_offset_ms: 6405},
      %Video.TimedPoint{lat: 53.568991, lon: 9.973851, time_offset_ms: 6738},
      %Video.TimedPoint{lat: 53.56899882335329, lon: 9.973879284431138, time_offset_ms: 6939},
      %Video.TimedPoint{lat: 53.569062603603605, lon: 9.973899603603604, time_offset_ms: 6939},
      %Video.TimedPoint{lat: 53.569063, lon: 9.9739, time_offset_ms: 7005},
      %Video.TimedPoint{lat: 53.569082, lon: 9.97394, time_offset_ms: 7339},
      %Video.TimedPoint{lat: 53.569121, lon: 9.974027, time_offset_ms: 7672},
      %Video.TimedPoint{lat: 53.569171, lon: 9.974134, time_offset_ms: 8006},
      %Video.TimedPoint{lat: 53.569223, lon: 9.974249, time_offset_ms: 8340},
      %Video.TimedPoint{lat: 53.569276, lon: 9.974377, time_offset_ms: 8673},
      %Video.TimedPoint{lat: 53.569335, lon: 9.974509, time_offset_ms: 9007},
      %Video.TimedPoint{lat: 53.569396, lon: 9.974643, time_offset_ms: 9340},
      %Video.TimedPoint{lat: 53.569461, lon: 9.974782, time_offset_ms: 9674},
      %Video.TimedPoint{lat: 53.569527, lon: 9.974919, time_offset_ms: 10008},
      %Video.TimedPoint{lat: 53.56959, lon: 9.975061, time_offset_ms: 10341},
      %Video.TimedPoint{lat: 53.569658, lon: 9.975206, time_offset_ms: 10675},
      %Video.TimedPoint{lat: 53.569727, lon: 9.975341, time_offset_ms: 11008},
      %Video.TimedPoint{lat: 53.569807, lon: 9.975461, time_offset_ms: 11342},
      %Video.TimedPoint{lat: 53.569889, lon: 9.975578, time_offset_ms: 11676},
      %Video.TimedPoint{lat: 53.569967, lon: 9.97569, time_offset_ms: 12009},
      %Video.TimedPoint{lat: 53.570047, lon: 9.975806, time_offset_ms: 12343},
      %Video.TimedPoint{lat: 53.570134, lon: 9.97592, time_offset_ms: 12676},
      %Video.TimedPoint{lat: 53.570226, lon: 9.976034, time_offset_ms: 13010},
      %Video.TimedPoint{lat: 53.570315, lon: 9.976145, time_offset_ms: 13344},
      %Video.TimedPoint{lat: 53.570408, lon: 9.976264, time_offset_ms: 13677},
      %Video.TimedPoint{lat: 53.570498, lon: 9.976376, time_offset_ms: 14011},
      %Video.TimedPoint{lat: 53.570582, lon: 9.976491, time_offset_ms: 14344},
      %Video.TimedPoint{lat: 53.57066, lon: 9.976612, time_offset_ms: 14678},
      %Video.TimedPoint{lat: 53.570747, lon: 9.976722, time_offset_ms: 15012},
      %Video.TimedPoint{lat: 53.570836, lon: 9.976828, time_offset_ms: 15345},
      %Video.TimedPoint{lat: 53.57092, lon: 9.97694, time_offset_ms: 15679},
      %Video.TimedPoint{lat: 53.570996, lon: 9.977055, time_offset_ms: 16012},
      %Video.TimedPoint{lat: 53.571069, lon: 9.977167, time_offset_ms: 16346},
      %Video.TimedPoint{lat: 53.571128, lon: 9.977259, time_offset_ms: 16680},
      %Video.TimedPoint{lat: 53.57114964564565, lon: 9.977289222222222, time_offset_ms: 16816}
    ]
  end
end