defmodule Data.AutoGenerated.Video.Rendered_7210b7ccddec805d100c7ad56d116ba7 do
  @moduledoc "#{"2018-01-01-cch: Umleitung Tiergartenstraße"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "2018-01-01-cch: Umleitung Tiergartenstraße"
  end

  @impl Video.Rendered
  def hash() do
    "7210b7ccddec805d100c7ad56d116ba7"
  end

  @impl Video.Rendered
  def length_ms() do
    43300
  end

  @impl Video.Rendered
  def sources() do
    [{"2021-08-01-freizeit9-anfang/GX012481", "00:00:03.070", :end}]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %Geo.BoundingBox{
      min_lon: 9.976396,
      min_lat: 53.557899,
      max_lon: 9.988784508982036,
      max_lat: 53.564104
    }
  end

  @impl Video.Rendered
  def renderer() do
    1
  end

  @impl Video.Rendered
  def recording_dates() do
    [%{text: "August 2021", timestamp: 0}]
  end

  @impl Video.Rendered
  # names derived from OpenStreetMap data, thus ODbL https://osmfoundation.org/wiki/Licence
  def street_names() do
    [
      %{timestamp: 0, text: "Gorch-Fock-Wall"},
      %{timestamp: 10941, text: "Jungiusstraße"},
      %{timestamp: 19281, text: "St. Petersburger Straße"},
      %{timestamp: 36295, text: "Messeplatz"},
      %{timestamp: 41299, text: "Rentzelstraße"}
    ]
  end

  @impl Video.Rendered
  def timed_polyline() do
    "}h}ceBajt`R?U`CsOl@~E{Sf@fGySZxG{SPdHySb@`H{Sx@pG{Sn@dIySt@nI{Sj@rHySP~H{STrI{SRjIySLjI{SLtIySTnI{SVnI{SX~IyS\\`J{S\\lIyS^vI{SVrI{SXnIySb@hI{Sf@pHySl@pG{Sd@nH{Sz@jHySfArH{SbA~GySj@jF{SFjF{SiAlFySeBdF{SwBzEyS_D`D{SaDjC{SyC`CySyCzB{S}CpBySuCjB{SuCnB{SqCrBySuCnB{S}CpBySuCpB{S{CpB{SuCdBySsCfB{SkCdBySsCjB{SuCpB{SuCvBySqCdB{SwClBySuCpB{SqCjC{SiCvCySqClB{SkCvCySwB~D{SwB`E{SkBxEySiBzE{SkBdFySkBvF{S{AjG{SeAtGyScAdG{ScAfGySmBlG{SwCpG{SiClGySeCjG{ScCjFySuBlG{SyBzF{SsBfGySuBnG{SyBbGySsBdG{SwB~F{SqBvFySqBnF{SoBhGySiBdG{SoB`G{SqBbGySqBjF{SmBlFySiBtG{SkBhGySaBlH{S}AbG{SwAlFyS{@nC{Sk@~BySw@tD{SyApD{SiBxDySwBrE{ScC`EyS{BfE{SyBlE{SmBfFySiBfF{SyB|EySyCdD{SyD\\{SsDiAyScD}A{SsCcByScDaB{SaDaB{SmCoBySuCoB{S_DkByScDcB{ScDgB{S}C}AySuCwA{SsCuAySsCoA{S_CkA{S}BaByS{BsB{SyB_ByS}B{A{S}A{A{Ss@c@yS"
  end
end
