defmodule Data.AutoGenerated.Video.Rendered_7cdf475232da6e5f3a3deb7e6a16020b do
  @moduledoc "#{"2026-03-17-jarrestrasse: Richtung Saarlandstraße"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "2026-03-17-jarrestrasse: Richtung Saarlandstraße"
  end

  @impl Video.Rendered
  def hash() do
    "7cdf475232da6e5f3a3deb7e6a16020b"
  end

  @impl Video.Rendered
  def length_ms() do
    40488
  end

  @impl Video.Rendered
  def sources() do
    [
      {"2023-04-02-br-wandsbek/GX015388", :start, :end},
      {"2023-04-02-br-wandsbek/GX015389", :start, "00:00:07.006"}
    ]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %{
      __struct__: Geo.BoundingBox,
      maxLat: 53.58818,
      maxLon: 10.033621,
      minLat: 53.58311999999999,
      minLon: 10.019044
    }
  end

  @impl Video.Rendered
  def renderer() do
    6
  end

  @impl Video.Rendered
  def recording_dates() do
    [%{text: "April 2023", timestamp: 0}]
  end

  @impl Video.Rendered
  def street_names() do
    [
      %{text: "Barmbeker Straße", timestamp: 0},
      %{text: "Jarrestraße", timestamp: 3336},
      %{text: "Saarlandstraße", timestamp: 35484}
    ]
  end

  @impl Video.Rendered
  def timed_polyline() do
    "_pmeeBgmobR?Q]{S[oBySq@kD{SeBsEyScCuD{S{Bq@{ScCj@yS{C`@{S}Ci@ySwCoD{S}B_G{SmB_HySwA}H{SiAyHySo@qI{S{AoH{Sc@aIyS}A{H{SwAmIySaAkI{SwAyH{SaA{HySq@gI{Sm@qIySy@qI{S{@qI{S_AmIySkB}F{SuAkHySgAoH{Sw@}H{Sw@cHyS_AiI{Su@kIySy@wH{SgA{H{SoAwHySo@cI{Sy@aIySsAmH{SyAuG{SwA}GySyA_I{SsAmHySw@iG{SeAiH{SgAaIySkAyH{SeAqIySmAyI{SwAcI{So@qIyS{@mI{Sy@uHySo@mH{Se@aH{Sq@wGySaAeI{SeAeIySeBgH{SqBqH{SiBqGySgBmG{SkAaIySaBcI{SuA}H{SeAmIyS_CaH{ScAqIySgAkI{SyAaI{SaBaHyS{AiH{SmB{GySeCeH{SmBeH{SyBsGySkBkG{S_@gIyS_CqF{SuAwG{SeAsHySeAkH{S_AcHySiAuG{SkAsG{SkBeFySy@sH{SeAcHySy@uG{SqB{H{SqAkGySaCoE{SsAyFyS}@wF{Ss@gF{Sw@mEyS_@yE{S]kDySKsB{So@kCsFSu@{Si@uCyS_A}E{ScA{FySuAgF{ScBaE{SsCoCySwCyA{S{BSySwAS{SeBC{S}BKyS}CV{SgDXySeBN{Si@@{Sc@KyS_BB{SgCZySaCp@{SqCH{S"
  end
end
