defmodule Data.AutoGenerated.Video.Rendered_8ea36cc9094ce21a0e95958c738d6e92 do
  @moduledoc "#{"ahrensburg-a6: U-Bahn Ahrensburg West → Zentrum"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "ahrensburg-a6: U-Bahn Ahrensburg West → Zentrum"
  end

  @impl Video.Rendered
  def hash() do
    "8ea36cc9094ce21a0e95958c738d6e92"
  end

  @impl Video.Rendered
  def length_ms() do
    65717
  end

  @impl Video.Rendered
  def sources() do
    [
      {"2022-10-16-ahrensburg2/GX014939", "00:01:35.329", "00:01:38.765"},
      {"2022-10-16-ahrensburg2/GX014904", "00:01:34.561", :end},
      {"2022-10-16-ahrensburg2/GX014905", :start, "00:00:28.128"},
      {"2022-10-15-ahrensburg/GX014881", "00:03:19.766", :end},
      {"2022-10-15-ahrensburg/GX014882", :start, :end},
      {"2022-10-15-ahrensburg/GX014883", :start, "00:00:13.614"}
    ]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %Geo.BoundingBox{
      minLon: 10.220332,
      minLat: 53.66378545345346,
      maxLon: 10.238984635110638,
      maxLat: 53.67283317823729
    }
  end

  @impl Video.Rendered
  def renderer() do
    3
  end

  @impl Video.Rendered
  def recording_dates() do
    [%{text: "Oktober 2022", timestamp: 0}]
  end

  @impl Video.Rendered
  # names derived from OpenStreetMap data, thus ODbL https://osmfoundation.org/wiki/Licence
  def street_names() do
    [%{timestamp: 0, text: "Waldemar-Bonsels-Weg"}, %{timestamp: 3701, text: "Hamburger Straße"}]
  end

  @impl Video.Rendered
  def timed_polyline() do
    "suljeBe|xnR?`@N_D`Cr@{SjCz@{SdC|@ySjCbA{ShCx@ySlCP{SfCw@{S|BoBySdBmB{SzLeBmEs@yBiJaBeE{SmAmCySk@yA{S_AmBgAFm@{Sh@{AySr@wB{SUuCyScAgC{SwAiD{SwAsDyS_B}D{SaBoEyScBkE{SeBoE{SgB{EySiByE{SkB{EySmBcF{SeByE{SqBuEySoBaF{SiBaFySmBaF{SqB_F{SkByEySkBsE{SmByEySsB_F{SmBuE{SmB}EySiB{E{SoB_FySsBaF{SoBuE{SkBwEySgB{E{SoBwEySmB_F{SqBkF{SqBaFySsBuE{SsBcFySsB}E{SmB}E{SmB{EySgB{E{SmBeFySqB_F{SoBaF{SkBcFyS}BiE{SkC{DySwBgF{SuBmF{SsBkFySiBmF{SuBqFySuBkF{SsBaF{SoB}EySoBiF{SiBaFySkBcF{SkBeF{SoB_FySuBcF{SqBeFySoBaF{SsBaF{SoBgFySgBaF{S}AkFySgB{F{SqBsF{SsBqFySoBoF{S{B_FySaCqF{SuByF{SmBkFySqBmF{SqBuFySyBoF{S_CwF{S_CsFySsBeF{SiFuMyJUg@wByBmF{SuBiFySyBkF{SyBoF{SkBaFySqBcF{ScBmEySuAwD{Sq@uD{SiBk@}JGM{SW]yS]s@{Sy@sAySkAyB{SoAsC{S{AeDyScBmD{S_B_EySeBkE{SgBkE{SmBkEySmBoE{SqBwEySkBgF{SmBiF{SsBcFySqBkF{SuBqFySsBmF{SmB_F{ScB{EySoBqF{SoBoFySuBsF{SuBiF{SsBeFySuBcF{SiBuFySkByF{SyAkG{SaBaFySgBoE{SeBoEyScAuE{SiAyE{SyAkEySsAoE{SgAaFySoAuE{S_BiE{SgBcEyS}AmD{SwAgDySsA_D{SeAyC{SqAuBySeBoA{Sw@yAySfA_CyLqEiKkrAmIkFq}@oFsH{SoS{g@yeDeR_e@a|BmSeh@}pCoCuGwh@qEyKkrAeFuOggBEuE{O"
  end
end
