defmodule Data.AutoGenerated.Video.Rendered_936d92c42595877d0925a822fdb40837 do
  @moduledoc "#{"2021-05-19-versuchsradweg-hallerstrasse: Hallerstraße Richtung Westen"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "2021-05-19-versuchsradweg-hallerstrasse: Hallerstraße Richtung Westen"
  end

  @impl Video.Rendered
  def hash() do
    "936d92c42595877d0925a822fdb40837"
  end

  @impl Video.Rendered
  def length_ms() do
    17202
  end

  @impl Video.Rendered
  def sources() do
    [
      {"2021-06-19-veloroute6/GX011884", "00:00:02.002", :end},
      {"2021-06-19-veloroute6/GX011885", :start, "00:00:13.447"}
    ]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %Geo.BoundingBox{
      min_lon: 9.979473523952096,
      min_lat: 53.572584,
      max_lon: 9.987941,
      max_lat: 53.572772
    }
  end

  @impl Video.Rendered
  def renderer() do
    1
  end

  @impl Video.Rendered
  def recording_dates() do
    [%{text: "Juni 2021", timestamp: 0}]
  end

  @impl Video.Rendered
  # names derived from OpenStreetMap data, thus ODbL https://osmfoundation.org/wiki/Licence
  def street_names() do
    [%{timestamp: 0, text: "Hallerstraße"}]
  end

  @impl Video.Rendered
  def timed_polyline() do
    "giydeBiur`R?BxH{SH`IyS?dI{S?bI{SB|HyS?rH{SBxG{SAhFySAnD{S?jC{SBhBySbB`CiD?^{S@vBySIrD{SGzE{SL~FySXxG{SNvH{SNhIySJvI{SDzI{SBhJyS@lJ{SDhJ{SLzJySBtJ{SEpJ{S?xJySNxJ{SJvJ{SH|JyS?~J{SAbK{S@hKySBjK{SDnK{S@nKySBrK{SHnK{SJ|KySN~K{SJzK{SHrKySBlK{SJ~JySH|J{SHhJ{SDbJySC|I{S[nI{S[fIyS?|AiE"
  end
end
