defmodule Data.AutoGenerated.Video.Rendered_a52e6b86a2e860db536c9d7d4438dae8 do
  @moduledoc "#{"2020-11-13-methfesselstrasse: Methfesselstraße"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "2020-11-13-methfesselstrasse: Methfesselstraße"
  end

  @impl Video.Rendered
  def hash() do
    "a52e6b86a2e860db536c9d7d4438dae8"
  end

  @impl Video.Rendered
  def length_ms() do
    16316
  end

  @impl Video.Rendered
  def sources() do
    [{"2021-12-25-velo2-rsw-elmshorn/GX013083", "00:03:02.049", "00:03:18.365"}]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %Geo.BoundingBox{
      maxLat: 53.582351,
      maxLon: 9.947489,
      minLat: 53.57970005389222,
      minLon: 9.945989476047904
    }
  end

  @impl Video.Rendered
  def coords() do
    [
      %Video.TimedPoint{lat: 53.58235042342343, lon: 9.947190522522524, time_offset_ms: 0},
      %Video.TimedPoint{lat: 53.582351, lon: 9.947228, time_offset_ms: 96},
      %Video.TimedPoint{lat: 53.58235, lon: 9.947335, time_offset_ms: 430},
      %Video.TimedPoint{lat: 53.582337, lon: 9.947408, time_offset_ms: 764},
      %Video.TimedPoint{lat: 53.582303, lon: 9.947455, time_offset_ms: 1097},
      %Video.TimedPoint{lat: 53.582248, lon: 9.947484, time_offset_ms: 1431},
      %Video.TimedPoint{lat: 53.582185, lon: 9.947489, time_offset_ms: 1764},
      %Video.TimedPoint{lat: 53.582141, lon: 9.947485, time_offset_ms: 2098},
      %Video.TimedPoint{lat: 53.582084, lon: 9.947475, time_offset_ms: 2498},
      %Video.TimedPoint{lat: 53.581973, lon: 9.947457, time_offset_ms: 2865},
      %Video.TimedPoint{lat: 53.58174, lon: 9.947411, time_offset_ms: 4100},
      %Video.TimedPoint{lat: 53.581703, lon: 9.947404, time_offset_ms: 4433},
      %Video.TimedPoint{lat: 53.581636, lon: 9.947394, time_offset_ms: 4767},
      %Video.TimedPoint{lat: 53.581567, lon: 9.947382, time_offset_ms: 5100},
      %Video.TimedPoint{lat: 53.581501, lon: 9.947375, time_offset_ms: 5434},
      %Video.TimedPoint{lat: 53.581439, lon: 9.947389, time_offset_ms: 5768},
      %Video.TimedPoint{lat: 53.581376, lon: 9.947404, time_offset_ms: 6101},
      %Video.TimedPoint{lat: 53.581309, lon: 9.947397, time_offset_ms: 6435},
      %Video.TimedPoint{lat: 53.58124, lon: 9.947381, time_offset_ms: 6768},
      %Video.TimedPoint{lat: 53.58117, lon: 9.947371, time_offset_ms: 7102},
      %Video.TimedPoint{lat: 53.581101, lon: 9.947352, time_offset_ms: 7436},
      %Video.TimedPoint{lat: 53.581032, lon: 9.947324, time_offset_ms: 7769},
      %Video.TimedPoint{lat: 53.580964, lon: 9.947294, time_offset_ms: 8103},
      %Video.TimedPoint{lat: 53.580904, lon: 9.947258, time_offset_ms: 8436},
      %Video.TimedPoint{lat: 53.580846, lon: 9.947213, time_offset_ms: 8770},
      %Video.TimedPoint{lat: 53.580784, lon: 9.947173, time_offset_ms: 9104},
      %Video.TimedPoint{lat: 53.580726, lon: 9.94713, time_offset_ms: 9437},
      %Video.TimedPoint{lat: 53.58067, lon: 9.947087, time_offset_ms: 9771},
      %Video.TimedPoint{lat: 53.580614, lon: 9.947046, time_offset_ms: 10104},
      %Video.TimedPoint{lat: 53.580561, lon: 9.947, time_offset_ms: 10438},
      %Video.TimedPoint{lat: 53.58051, lon: 9.94694, time_offset_ms: 10772},
      %Video.TimedPoint{lat: 53.580478, lon: 9.9469, time_offset_ms: 11105},
      %Video.TimedPoint{lat: 53.580458, lon: 9.946884, time_offset_ms: 11439},
      %Video.TimedPoint{lat: 53.580437, lon: 9.94688, time_offset_ms: 11772},
      %Video.TimedPoint{lat: 53.580403, lon: 9.946857, time_offset_ms: 12106},
      %Video.TimedPoint{lat: 53.58036, lon: 9.946802, time_offset_ms: 12440},
      %Video.TimedPoint{lat: 53.58031, lon: 9.946741, time_offset_ms: 12773},
      %Video.TimedPoint{lat: 53.580261, lon: 9.94667, time_offset_ms: 13107},
      %Video.TimedPoint{lat: 53.580209, lon: 9.946596, time_offset_ms: 13440},
      %Video.TimedPoint{lat: 53.580158, lon: 9.946517, time_offset_ms: 13774},
      %Video.TimedPoint{lat: 53.5801, lon: 9.946454, time_offset_ms: 14108},
      %Video.TimedPoint{lat: 53.580037, lon: 9.946386, time_offset_ms: 14441},
      %Video.TimedPoint{lat: 53.579981, lon: 9.946313, time_offset_ms: 14775},
      %Video.TimedPoint{lat: 53.579922, lon: 9.946239, time_offset_ms: 15108},
      %Video.TimedPoint{lat: 53.579862, lon: 9.946168, time_offset_ms: 15442},
      %Video.TimedPoint{lat: 53.579798, lon: 9.9461, time_offset_ms: 15776},
      %Video.TimedPoint{lat: 53.579736, lon: 9.946031, time_offset_ms: 16109},
      %Video.TimedPoint{lat: 53.57970005389222, lon: 9.945989476047904, time_offset_ms: 16316}
    ]
  end
end
