defmodule Data.AutoGenerated.Video.Rendered_d7d9e00c93dbe75b9a0714fa3ae878c3 do
  @moduledoc "#{"2024-02-15-vierlaender-damm: vom Tiefstack zur Billhorner Brückenstraße"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "2024-02-15-vierlaender-damm: vom Tiefstack zur Billhorner Brückenstraße"
  end

  @impl Video.Rendered
  def hash() do
    "d7d9e00c93dbe75b9a0714fa3ae878c3"
  end

  @impl Video.Rendered
  def length_ms() do
    89571
  end

  @impl Video.Rendered
  def sources() do
    [
      {"2024-01-27-bergedorf/GX016745", "00:00:12.010", "00:00:39.006"},
      {"2024-01-27-bergedorf/GX016745", "00:00:40.240", "00:01:43.082"}
    ]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %Geo.BoundingBox{minLon: 10.032534, minLat: 53.529178, maxLon: 10.067858, maxLat: 53.539147}
  end

  @impl Video.Rendered
  def renderer() do
    3
  end

  @impl Video.Rendered
  def recording_dates() do
    [%{timestamp: 0, text: "Januar 2024"}]
  end

  @impl Video.Rendered
  def street_names() do
    [
      %{timestamp: 0, text: "Ausschläger Allee"},
      %{timestamp: 47204, text: "Vierländer Damm"},
      %{timestamp: 68221, text: "Billhorner Röhrendamm"},
      %{timestamp: 83900, text: ""}
    ]
  end

  @impl Video.Rendered
  def timed_polyline() do
    "sddbeBcxneR?}CjCySyCfD{SyCnDySwCvD{SiCtE{S{BtFySuClE{S_DlEySyCxE{S{C`F{SyCxFySuCbG{SoCnGySiCdH{S_CpH{S}BpHySqB`I{SyAvIyScAhJ{S{@nJ{Sq@vJySk@~J{Sg@~JySe@dK{Si@fK{Se@dKySc@bK{S]xJySg@pJ{Si@nJ{Se@jJySa@fJ{S_@lJySa@hJ{Se@`J{Sc@zIyS_@nI{S_@bIySa@bI{S[~H{SSpHySOfH{SSxGySq@lG{Sk@~G{S_@lHyS]zH{Sa@jIySe@zI{Sa@`J{Sa@`JyS[~I{Sa@~IySc@zI{Sa@`J{Sc@zIySg@vI{Sq@tIySs@jI{So@`I{Sq@zHySq@|H{So@jHySm@nH{Sk@jH{So@lHySo@jH{So@nHySq@lH{Sm@jH{Sm@nHySo@nH{So@lHyS_AjH{SeAdH{SaA|GyS{@lG{Ss@zEySe@tD{SW~C{SWnEqABP{FLpBySJrD{SAjFyS_@bG{Sk@fG{Su@nGyS}@nG{Sy@pGyS}@rG{S}@nG{SmAdGySaAlG{S}@rGySaAxG{S_AlG{ScAbGyS{@fF{Ss@dEySe@fF{Sm@tF{Su@~FyS{@jG{Sy@hGySy@rG{SaAxG{Sw@nGyS}@rG{Sy@xGySs@vG{S{@vG{So@nFySItD{Sc@tFySaAlG{SiArE{Sg@pFySg@hG{Ss@rFySaA`E{SgAdD{Sk@nEySe@jE{Ss@zDyS}@lC{Si@`E{Su@`FySg@xF{Su@vFyS{@nF{S{@dF{Sq@bFySg@dF{Sq@xEySo@xE{Sg@nF{Ss@dFySo@hF{Su@dFyS{@~E{S{@|E{Sa@zEySQxE{SLvEyS_@|F{S_AtG{SaAjHySgArH{SgA`IySiAbI{SgA`I{SkApHySiArH{SiAnHySqApH{SiAnH{SmAbIySaAbI{S_AlIySgAfI{SgAbI{ScA`IySaApH{SiA`IyScAbI{Sy@pI{Sg@tIySYzI{SUbJyS[bJ{S[dJ{SY~IySUnI{SWvHySS`H{SQpG{SS|FySOhF{SKtEySM|D{SMfD{SKrCySG`C{SGjBySG|A{SEpA{SIrAySQbD{SQrFySCbH{SBbI{SQhIyS_@vI{SY~IyS]lJ{S[nJ{S[jJySWjJ{SQ~IySe@~I{S_@`J{S]~IySo@vI{SgAlIySuAfI{S{A|H{SmBtHySuBpH{SaChHySgCbH{SyCzG{SqCzGySuC~G{SqCvGySoCrG{SwCpG{SwCpGySmCpG{SkCjGySqCtG{SqCpG{SkClGySeClG{S_CnGyScChG{ScClG{SaCfGyS_CzF{SwBxFyS}BxF{ScC~F{SgC`GySgC`G{ScCdGyS{BdG{SaCbG{SkCvFySsC~E{SsCrEySyC~D{S}CpD{SyC`EySiCbE{SiCvDySkCnC{S{CfC{SyCdCySaDpB{SgDpBySaDfB{SyC|A{SeDnBySaDtA{SgDxAySgD|A{ScDzA{SqC|AySmCzA{SwCtAyScD~A{SeD`B{SaDnBySyCdC{SuCxCySiCtD{ScCbE{SqC`EySkDjC{SwD@yS"
  end
end
