defmodule Data.AutoGenerated.Video.Rendered_f20f5605d4689a7e44a8db9f60bca726 do
  @moduledoc "#{"lexikon/bettel-Und-bedarfs-ampel: entlang des Isebekkanals zum Weidenstieg"}

# AUTOGENERATED. To update this file, run mix velo.videos.generate.
# See Video.Rendered for functionality.
"
  @behaviour Video.Rendered
  @impl Video.Rendered
  def name() do
    "lexikon/bettel-Und-bedarfs-ampel: entlang des Isebekkanals zum Weidenstieg"
  end

  @impl Video.Rendered
  def hash() do
    "f20f5605d4689a7e44a8db9f60bca726"
  end

  @impl Video.Rendered
  def length_ms() do
    52915
  end

  @impl Video.Rendered
  def sources() do
    [
      {"2023-10-29-lenhart/GX016643", "00:00:11.211", :end},
      {"2023-10-29-lenhart/GX016644", :start, "00:00:36.904"}
    ]
  end

  @impl Video.Rendered
  def rendered?() do
    true
  end

  @impl Video.Rendered
  def bbox() do
    %Geo.BoundingBox{
      minLon: 9.961606,
      minLat: 53.57065976646707,
      maxLon: 9.976086540540539,
      maxLat: 53.57812242342342
    }
  end

  @impl Video.Rendered
  def renderer() do
    3
  end

  @impl Video.Rendered
  def recording_dates() do
    [%{timestamp: 0, text: "Oktober 2023"}]
  end

  @impl Video.Rendered
  def street_names() do
    [
      %{timestamp: 0, text: "Grindelberg"},
      %{timestamp: 1466, text: "Kaiser-Friedrich-Ufer"},
      %{timestamp: 23350, text: ""},
      %{timestamp: 26019, text: "Goebenbrücke"},
      %{timestamp: 28021, text: ""},
      %{timestamp: 36027, text: "Bundesstraße"},
      %{timestamp: 40030, text: ""},
      %{timestamp: 51706, text: "Weidenstieg"}
    ]
  end

  @impl Video.Rendered
  def timed_polyline() do
    "swceeBmp{_R?j@FeG`BvC{S~AlE{ShBdFyS|AlF{S~AzFyS~AdG{StApG{S`BpGySjBrG{SpBpGySnBtG{StBnG{SvBrGySpB`H{SpBnGySzA~F{Sr@`H{SlAvFySdBlF{SbBfGySnBlF{StB~F{SnBpGySnBpG{S`BlGyShB|F{SbBbFySdBbE{SbBzE{S~AxDySfBjF{StA`EySvAjE{SlAlF{SnAjDyS|AzE{SbBvFySfBvF{StBnF{ShArDySj@xB{Sl@pByS^bB{S\\lB{SZ`BySVvA{SHx@ySt@`EqKBL{SHrAySb@rB{SbArBySlAhC{SjAvC{SnAdDySpAjE{SdAlEySvAnE{SvAbF{SrAzEyS~ArE{SbB`FySdB`F{SvAvE{S`BvDySzApD{Sv@tDySv@hE{SbA`F{SdAzEySvAdF{S~ApFySfBjF{ShBnF{SjBpFyShBpF{SdBvEyS`BdF{SlAnE{S`AvDyS~AzF{SrBnGySdBrF{ShB`G{SjBrFyS~A`F{ShApEySvA~E{SzAjF{SlAfEySrAvE{S`BtFySrBtF{SnBrF{SlBpFySbBrF{SrA`FySlAtE{SfB`F{ShBdFyShB`F{SfBrEySdBbE{SbB|D{SvAlDyShAxC{SnAnCySpAtB{Sx@fB{Sl@lAySd@hA{S^~AySr@dB{SlAbC{StAlCySdAzB{SpAvCyShB~C{SxA`D{SzAjCySdBzB{S`BvBySfBfC{SfB`C{SlBjCySfBfC{SjBjBySbBbB{SnBtB{SvB|ByS|B`C{ShB|BySrBjC{ShBjC{SpBvCySrB`D{SbCpCySjC`C{SfCdB{SzBnBySbCfB{S~BpBySdCvB{S`CfB{S`CdCySlCvB{ShCvBySrBhB{SfCvB{SdCdCyS|B`C{S|BnBySjB~A{SrBfC{SvBzBySnBhB{SbBvAyS~Ar@{SlAE_L"
  end
end
