rootProject.name = 'mlt-converter'

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            from(files("/maplibre-tile-spec/java/gradle/libs.versions.toml"))
        }
    }
}

include(":mlt-core")
project(":mlt-core").projectDir = file("/maplibre-tile-spec/java/mlt-core")
