FROM debian:trixie-20251020-slim AS downloader

ARG SVTAV1_REPO=https://gitlab.com/AOMediaCodec/SVT-AV1/-
ARG SVTAV1_VERSION=b8f0f823badf67ae7ba7563cab6fdabfbf70cca1
# ARG SVTAV1_REPO=https://github.com/BlueSwordM/svt-av1-psyex
# ARG SVTAV1_VERSION=d1dbfba23beb1ff7a7f5129fd303e4cf5d397eb0

# ARG FFMPEG_VERSION=7.1
ARG BLUR_VERSION=2febf37aed95188ef829cfe156aad016a51a54a6
ARG RIFE_VERSION=ed9e00781d0a9a727838437d6938afdbd49a8cbd

RUN mkdir -p /downloads/

RUN  \
  apt-get update && \
  apt-get install -y --no-install-recommends \
  ca-certificates \
  git \
  wget \
  && rm -rf /var/lib/apt/lists/*

# RUN \
#   cd /downloads/ && \
#   wget https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.gz -O ffmpeg.tar.gz && \
#   tar zxf ffmpeg.tar.gz && rm ffmpeg.tar.gz && mv ffmpeg-${FFMPEG_VERSION} ffmpeg
RUN cd /downloads/ && \
  wget https://github.com/breunigs/ffmpeg/archive/refs/heads/frei0r-mixers-svt-multipass.tar.gz && \
  tar zxf frei0r-mixers-svt-multipass.tar.gz && rm frei0r-mixers-svt-multipass.tar.gz && mv *-frei0r-mixers-svt-multipass ffmpeg && \
  echo "force rebuild 1"


RUN cd /downloads/ && \
  wget https://github.com/breunigs/frei0r-blur-from-json/archive/${BLUR_VERSION}.tar.gz && \
  tar zxf ${BLUR_VERSION}.tar.gz && rm ${BLUR_VERSION}.tar.gz && mv frei0r-blur-from-json-${BLUR_VERSION} blur

#github
# RUN cd /downloads/ && \
#   wget ${SVTAV1_REPO}/archive/${SVTAV1_VERSION}.tar.gz && \
#   tar zxf ${SVTAV1_VERSION}.tar.gz && rm ${SVTAV1_VERSION}.tar.gz && mv *-${SVTAV1_VERSION} svtav1
#gitlab
RUN cd /downloads/ && \
  wget ${SVTAV1_REPO}/archive/${SVTAV1_VERSION}/SVT-AV1-${SVTAV1_VERSION}.tar.gz && \
  tar zxf SVT-AV1-${SVTAV1_VERSION}.tar.gz && rm SVT-AV1-${SVTAV1_VERSION}.tar.gz && mv *-${SVTAV1_VERSION} svtav1


RUN cd /downloads/ && \
  git clone https://github.com/breunigs/frei0r-rife-transition --recurse-submodules rife && \
  cd rife && \
  git reset --hard ${RIFE_VERSION}

RUN mkdir -p cd /downloads/pgo && \
  cd /downloads/pgo && \
  wget https://veloroute.hamburg/videos/rendered/svtav1pgo.y4m

FROM debian:trixie-20251020-slim AS blur
WORKDIR /build/

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
  cmake \
  frei0r-plugins-dev \
  g++ \
  libboost-dev \
  libboost-iostreams-dev \
  libvips-dev \
  make \
  rapidjson-dev \
  && rm -rf /var/lib/apt/lists/*

COPY --from=downloader /downloads/blur/ /build/.
RUN cmake . && make

FROM debian:trixie-20251020-slim AS rife
WORKDIR /build/

RUN apt-get update \
  && apt-get install --yes --no-install-recommends \
  bash \
  cmake \
  frei0r-plugins-dev \
  g++ \
  git \
  libvulkan-dev \
  libwebp-dev \
  make \
  && rm -rf /var/lib/apt/lists/*

COPY --from=downloader /downloads/rife/ /build/.
RUN ./build.sh

FROM debian:trixie-20251020-slim AS ffmpeg-build

RUN \
  apt-get update \
  && apt-get install -y --no-install-recommends \
  autoconf \
  automake \
  binutils \
  build-essential \
  ca-certificates \
  cargo \
  cargo-c \
  cmake \
  curl \
  frei0r-plugins-dev \
  git \
  libaom-dev \
  libdav1d-dev \
  libffmpeg-nvenc-dev \
  libfontconfig1-dev \
  libfreetype-dev \
  libharfbuzz-dev \
  libssl-dev \
  libtool \
  libva-dev \
  libwebp-dev \
  libx264-dev \
  libx265-dev \
  libzimg-dev \
  make \
  meson \
  nasm \
  ninja-build \
  pkg-config \
  rustc \
  yasm

ENV PREFIX=/build
RUN mkdir ${PREFIX}
ENV CFLAGS=-O3
ENV CXXFLAGS="$CFLAGS"
ENV LDFLAGS="$LDFLAGS -L${PREFIX}/lib"
ENV LD_LIBRARY_PATH="${PREFIX}/lib"
ENV PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig"

COPY --from=downloader /downloads /downloads/

RUN cd /downloads/svtav1/Build/linux && \
  ./build.sh \
  --native \
  --static \
  --release \
  --enable-lto \
  --enable-pgo \
  --pgo-videos=/downloads/pgo \
  --prefix=${PREFIX} \
  --install

RUN cd /downloads/ffmpeg && \
  ./configure \
  --prefix="${PREFIX}" \
  --extra-libs="-lm -lpthread" \
  --extra-cflags="-I${PREFIX}/include -w -O3" \
  --extra-ldflags="-L${PREFIX}/lib" \
  --ld="g++" \
  --enable-version3 \
  --enable-gpl \
  --enable-frei0r \
  --enable-libaom \
  --enable-libdav1d \
  --enable-libfontconfig \
  --enable-libfreetype \
  --enable-libharfbuzz \
  --enable-libsvtav1 \
  --enable-libwebp \
  --enable-libx264 \
  --enable-libx265 \
  --enable-libzimg \
  --enable-vaapi \
  --disable-debug \
  --disable-doc \
  --disable-ffplay \
  --disable-ffprobe && \
  make -j $(nproc) && make install && make distclean



FROM debian:trixie-20251020-slim AS runner
RUN \
  apt-get update && \
  apt-get install -y --no-install-recommends \
  adduser \
  i965-va-driver \
  libaom3 \
  libboost-iostreams1.83.0 \
  libc6 \
  libdav1d[0-9]+ \
  libva-drm2 \
  libva2 \
  libvips42 \
  libvulkan[0-9]+ \
  libwebp[0-9]+ \
  libwebpmux3 \
  libx264-[0-9]+ \
  libx265-[0-9]+ \
  libzimg2 \
  mesa-vulkan-drivers \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /usr/lib/frei0r-1/
COPY --from=blur /build/jsonblur.so /usr/lib/frei0r-1/
COPY --from=rife /build/rife_transition.so /usr/lib/frei0r-1/
COPY --from=ffmpeg-build /build/bin/ffmpeg /usr/bin/
COPY --from=ffmpeg-build /build/lib/libSvtAv1Enc.* /lib/x86_64-linux-gnu/
WORKDIR /workdir

ARG RENDER_GID
ARG GID
ARG UID
RUN addgroup --gid ${RENDER_GID} render && \
  addgroup --gid ${GID} dummy && \
  useradd -s /bin/bash -G render,video -g ${GID} -u ${UID} dummy
USER dummy

CMD ["/usr/bin/ffmpeg"]
