name: Testing
permissions:
  contents: read

env:
  MIX_ENV: test
  SHELL: /bin/sh

on:
  push:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup mise
        uses: jdx/mise-action@v2
        with:
          cache: true

      - name: Cache mix deps restore
        uses: actions/cache/restore@v3
        id: cache-mix-deps
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock', '.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - name: Cache mix deps save
        uses: actions/cache/save@v3
        if: steps.cache-mix-deps.outputs.cache-hit != 'true'
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('mix.lock', '.tool-versions') }}

      - run: mkdir -p /home/runner/work/veloroute/videos

      - run: mix compile
      - run: mix format --check-formatted
      - run: mix velo.setup ci
      - run: mix test --exclude requires_mount
